spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/init.sql
      data-locations: classpath*:db/data.sql
  jpa:
    show-sql: true
